# Generated by Django 4.0.5 on 2022-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('accomodation_type', models.CharField(max_length=50)),
                ('n_room_places', models.IntegerField()),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
            ],
        ),
    ]
