# Generated by Django 4.0.5 on 2022-06-17 09:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='accomodation_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='children',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='n_room_places',
        ),
        migrations.AddField(
            model_name='customer',
            name='accommodation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='booking_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kids',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_rooms_sites',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='adults',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
