# Generated by Django 4.0.5 on 2022-06-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customer_accomodation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adults',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
