# Generated by Django 4.0.5 on 2022-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='booking_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
