# Generated by Django 4.0.5 on 2022-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_booking_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
