# Generated by Django 4.0.5 on 2022-06-07 23:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_rooms_sites',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_of_accomodation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
