# Generated by Django 4.0.5 on 2022-06-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customer_adults_customer_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adults',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kids',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
