# Generated by Django 4.0.5 on 2022-06-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customer_adults_alter_customer_kids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='type_of_accomodation',
            new_name='accomodation',
        ),
    ]
