# Generated by Django 4.0.5 on 2022-06-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_type_of_accomodation_customer_accomodation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='accomodation',
            new_name='accommodation',
        ),
    ]
